### ISSUE TITLE
feat: add pin setup command

### ISSUE THREAD

**Issue by fourcube** [fourcube/spidev#15]
## Description
For SPI to work, the user needs to decide which pins the RPi should use for communication with the target IC (*integrated circuit*; also known as the *Slave*).

The pin setup should be a command, because it can change over the course of a program. It is typically executed as the first command of a program.

The pin setup command component should provide the following inputs. A pin picker could simply be a dropdown to choose from one of the 40 available pins. 

| Input | Input Type | Description | 
| ----- | ----------- | ------------|
| SCLK | Pin Picker | **S**erial **cl**oc**k** pin which the master uses for synchronizing the communication | 
| MISO | Pin Picker | **M**aster **I**nput **S**lave **O**utput pin. This is where the master sends data to the slave. | 
| MOSI | Pin Picker | **M**aster **O**utput **S**lave **I**nput pin. This is where the master receives data from the slave. | 
| CS    | Pin Picker | A pin that selects the active chip. An IC can provide multiple slaves which are chosen by a logic **0** ('LOW') on the CS pin. | 

## Messages

The `pin_setup` WebSocket message should take the physical ids of four pins as its arguments. The order should be as following:

- SCLK
- MISO
- MOSI
- CS

## Tasks
- [ ] Implement pin picker component
- [x] Create `pin_setup` command in the `model.ts` and `messages.ts`
- [x] Stub `pin_setup` command on the backend
